## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np

arr1 = np.arange(10,41)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [2]:
 import numpy as np

arr2 = np.arange(220,251)
arr2

array([220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
       233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
       246, 247, 248, 249, 250])

In [3]:
import numpy as np

print(np.add(arr1, arr2))
#arr3 = sum(arr1, arr2)
#arr3

[230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [4]:
arr3 = np.arange(100, 100 + 10*7).reshape(10, 7)
arr3

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate three-dimensional array (3x3x3) with random floats.

In [5]:
num_arr = np.random.rand(3,3,3)

num_arr

array([[[0.46115884, 0.9855575 , 0.88134784],
        [0.77788519, 0.65388875, 0.81185217],
        [0.60914463, 0.55099981, 0.44227732]],

       [[0.49274518, 0.28684938, 0.63368979],
        [0.05630861, 0.32823685, 0.64320153],
        [0.72403416, 0.72922186, 0.67580232]],

       [[0.28010591, 0.83160014, 0.03192682],
        [0.54207672, 0.84587088, 0.10729513],
        [0.76514158, 0.14370259, 0.11137811]]])

4 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [6]:
#numbers
numbers = np.arange(1,50,2)
#numbers2
numbers2 = np.arange(2,51,2)


result_multiply = numbers * numbers2
result_multiply

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

5 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [7]:
two_arr = np.random.randint(1, 1000, size=(40, 5))

query = np.where((two_arr%2==0) & (two_arr%5==0))
result = two_arr[query]

result

array([340, 860, 360, 380,  40, 420, 740, 830, 250, 100, 860, 480, 590,
       880, 950, 410,  60, 610, 250])